# Generated by Django 6.0.1 on 2026-02-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_master',
        ),
    ]
