# Generated by Django 6.0.1 on 2026-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CAR',
            },
        ),
    ]
