# Generated by Django 6.0.1 on 2026-02-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
