# Generated by Django 6.0.1 on 2026-02-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeEmail', models.EmailField(max_length=254)),
                ('employeePhone', models.CharField(max_length=100)),
                ('employeeSalary', models.IntegerField()),
                ('employeeStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='employeeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeAddress', models.CharField(max_length=100)),
                ('employeePosition', models.CharField(max_length=100)),
                ('employeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.employee')),
            ],
            options={
                'db_table': 'employeeprofile',
            },
        ),
    ]
