# Generated by Django 6.0.1 on 2026-02-06 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_employee_employeeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=100)),
                ('orderDate', models.DateField()),
                ('orderStatus', models.BooleanField(default=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
