# Generated by Django 6.0.1 on 2026-02-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_user_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('cityCode', models.CharField(max_length=10)),
                ('countryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
