# Generated by Django 6.0.1 on 2026-02-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0002_alter_founditem_user_alter_lostitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='Test1.test1user'),
        ),
    ]
